name: Deploy

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Allow postinstall/build scripts
        run: pnpm config set ignore-scripts false

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Deploy via gh-pages CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run deploy