name: Deploy

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - ".github/**"
      - "package.json"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps (CI)
        run: npm ci

      - name: Patch warnings (optional but helps)
        run: |
          npx update-browserslist-db@latest || true

      - name: Ensure Babel plugin present
        run: npm i -D @babel/plugin-proposal-private-property-in-object

      - name: Build
        run: npm run build
        env:
          CI: true

      - name: Configure Git identity
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Deploy via gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy