name: Deploy

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - ".github/**"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup npm
        uses: npm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Allow postinstall/build scripts
        run: npm config set ignore-scripts false

      - name: Install deps
        run: npm install --frozen-lockfile

      - name: Deploy via gh-pages CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy